version: '3.8'

services:
  # Next.js Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mp_customers_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET:-your-strong-secret-key}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - MAIL_HOST=${MAIL_HOST:-smtp.sendgrid.net}
      - MAIL_USERNAME=${MAIL_USERNAME:-apikey}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM_ADDRESS=${MAIL_FROM_ADDRESS:-deployer72@gmail.com}
      - TO_EMAIL=${TO_EMAIL:-tarikuka.aa@gmail.com}
      - renewPassword=${RENEW_PASSWORD:-masterRenewPass}
    ports:
      - "3000:3000"
